version: 2

jobs:
  install:
    working_directory: ~/deepmapper
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - attach_workspace:
          at: ~/deepmapper
      - run:
          name: NPM Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/deepmapper
          paths: ./node_modules
  lint:
    working_directory: ~/deepmapper
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/deepmapper
      - run:
          name: Lint
          command: npm run lint:ci
  test:
    working_directory: ~/deepmapper
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/deepmapper
      - run:
          name: Test
          command: npm run test:ci

workflows:
  version: 2
  install_lint_test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
